#!/bin/bash

#BSUB -a openmpi                        # tell lsf this is an openmpi job
#BSUB -c 9000000                        # total cpu time for job (sum of all processes ?)
#BSUB -n 20                              # number of tasks in job
#BSUB -R "affinity[core(1):cpubind=core:distribute=balance]"
#BSUB -R rusage[mem=100000]         # amount of total memory in MB for all processes
#BSUB -J lusch_hyp                   # job name
#BSUB -e errors.%J                  # error file name in which %J is replaced by the job ID
#BSUB -o output.%J                  # output file name in which %J is replaced by the job ID
#BSUB -q normal
##BSUB -q gpu_p100 # normal                 # choose the queue to use: normal or large_memory
#BSUB -B                        # email job start notification
#BSUB -N                        # email job end notification
#BSUB -u shawnpan@umich.edu     # email address to send notifications

##BSUB -R "select[ngpus>0] rusage[ngpus_excl_p=4]" # if I use gpu_p100


cd ../../EXAMPLES/lusch/2d_simple_lusch2017_noise_level_0/hyp/


mpirun python3 cv_kdmd_hyp_2d_lusch.py


